services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Datadog2024!"
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/usr/src/app/init.sql
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & 
        sleep 30 && 
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Datadog2024! -i /usr/src/app/init.sql -C &&
        wait
  food-outlet-api:
    build:
      context: .
    container_name: food-outlet-api
    depends_on:
      - sqlserver
    labels:
      com.datadoghp.tags: '[{"env": "dev", "service": "food-outlet-api", "version": "1.0"}]'
    environment:
      DATABASE_HOST: sqlserver
      DATABASE_PORT: 1433
      DATABASE_NAME: FoodOutlet
      DATABASE_USER: sa
      DATABASE_PASSWORD: Datadog2024!
      DD_SERVICE: food-outlet-api
      DD_ENV: dev
      DD_VERSION: 1.0
      DD_TRACE_ENABLED: true
      DD_LOGS_INJECTION: true
      DD_AGENT_HOST: "datadog-agent"
      DD_TRACE_AGENT_PORT: "8126"
    ports:
    - "8080:5000"